

HIDEOUT_KEY = "F5"
LOGOUT_KEY = "F1"
STASH_KEY = "!+^F2"
INV_LOCK_TOGGLE_MENU_KEY = "!+^F3"
MACRO_TRIGGER_KEY = "RButton"
# MACRO_TRIGGER_KEY = "Space"
MANUAL_TOGGLE_FLASK_KEY = "^+!F5"
LEVEL_GEM_KEY = "!+^F6"
GET_POS_KEY = "!a"
GUILD_HIDEOUT_KEY = "F4"
GEM_SWAP_KEY = "!+^F1"
FAST_CLICK_TOGGLE = "!+^F4"

#TODO put proper place
GEM_LEVEL_X = 2475
GEM_LEVEL_Y = 280
LEVEL_GEM_CLICK_OLD_MOUSE_POS = True